name: ShopTrack
description: "A new ShopTrack Flutter Project. Connected to Render(Django Framework and Python), MongoDB for Database"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.2
#  http: ^1.1.0
#  shared_preferences: ^2.2.2
#  provider: ^6.0.5
#  flutter_secure_storage: ^9.0.0
#  intl: ^0.18.1
#  pdf: ^3.7.1
#  path_provider: ^2.1.1
#  share_plus: ^7.0.0
#  connectivity_plus: ^5.0.1
#  universal_html: ^2.2.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  pdf: ^3.7.1
  path_provider: ^2.1.1
  share_plus: ^7.0.0
  connectivity_plus: ^5.0.1
  universal_html: ^2.2.4
  path_provider_platform_interface: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700