name: ShopTrack
description: "A new ShopTrack Flutter Project. Connected to Render(Django Framework and Python), MongoDB for Database"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  flutter_image_compress: ^2.1.0
  path: ^1.8.3
  confetti: ^0.7.0
  mask_text_input_formatter: ^2.7.0
  pdf: ^3.7.1
  share_plus: ^7.0.0
  connectivity_plus: ^5.0.1
  universal_html: ^2.2.4
  path_provider_platform_interface: ^2.1.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.3
  sqflite: ^2.3.2
  file_picker: ^6.1.1
  flutter_local_notifications: ^16.3.0+1
  email_otp: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700